### ISSUE TITLE
add genders from csv

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#102]
I have used Namsor to identify the approx. 4000 persons without a gender. The result is here and could be used to update the PMB: 
https://docs.google.com/spreadsheets/d/1DkJoIK-7pZ56K_6rEt0PoFmr-hMdoPsc673KH2uDMFA/edit#gid=1373209059

**Comment by csae8092** [comment]
@martinantonmueller  could you pleaes add column header "id", "name", "gender" to the spreadsheet?
Thank you!!!

**Comment by martinantonmueller** [comment]
i've removed the column name and added "id" and "gender"

**Comment by martinantonmueller** [comment]
Thank you!!!
