### ISSUE TITLE
image credit/attribution

### ISSUE THREAD

**Issue by csae8092** [arthur-schnitzler/pmb-service#111]
find a way to provide this

**Comment by martinantonmueller** [comment]
on commons every image has this information in html-format, cf. the button "Einbinden" and then the checkbox "HTML" on the right: 
[https://commons.wikimedia.org/wiki/File:Alexander_Landesberg_%E2%80%93_Unsere_einstigen_Mitarbeiter_(1)_1893_R._Weber_(Der_Floh).jpg](https://commons.wikimedia.org/wiki/File:Alexander_Landesberg_%E2%80%93_Unsere_einstigen_Mitarbeiter_(1)_1893_R._Weber_(Der_Floh).jpg)

there must be some way to retrieve this via the API:
https://commons.wikimedia.org/wiki/Commons:API

**Comment by csae8092** [comment]
as @martinantonmueller 
wir könnten jetzt einfach davon ausgehen, dass alle unsere personen gemeinfreie fotos haben – dann wäre das mit den credits nicht wichtig. aber weil das systematisch implementiert gehört, ist der link als beleg noch nicht richtig, weil da ist man beim bild, nicht aber bei den credits. für den angeführten popper-lynkeus wäre der link der hier: https://commons.wikimedia.org/wiki/File:Josef_Popper-Lynkeus_1917.jpg – da sehe ich die bildrechte und den urheber etc.

I quess this should be doable
