### ISSUE TITLE
image urls

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#112]
Currently the TEI-export for the image of "Karl Lamprecht" looks like this:

`<graphic url="https://commons.wikimedia.org/w/index.php?title=Special:Redirect/file/Karl Lamprecht.jpg&amp;width=400"/>`

no clue why it's so complicated and why the width is supplied. Problem is the &amp; as this makes the TEI-export invalid. On Wikimedia commons the address of the same image is listed as:

`https://upload.wikimedia.org/wikipedia/commons/c/c2/Karl_Lamprecht.jpg`

let's try another image:
`<graphic url="https://commons.wikimedia.org/w/index.php?title=Special:Redirect/file/Alexander Landesberg – Unsere einstigen Mitarbeiter (1) 1893 R. Weber (Der Floh).jpg&amp;width=400"/>`

again the file is flagged red in XML. In commons the URL is:
`https://upload.wikimedia.org/wikipedia/commons/f/f9/Alexander_Landesberg_%E2%80%93_Unsere_einstigen_Mitarbeiter_%281%29_1893_R._Weber_%28Der_Floh%29.jpg`

so with some output-escaping, that can make the URL valid. But the problem seems to be the f/f9-part which can not be derived from wikidata. I'll investigate further

**Comment by martinantonmueller** [comment]
turns out the part before the filename are first and the second chars of [MD5 hashsum](http://www.md5.cz/)

this php-function gets shorter urls:
```
function getWikimediaImageURL($aFilename) {
     #-- Example:  $aURLString = getWikimediaImageURL('Fortuna Düsseldorf.svg');    
     $aFilename = str_replace( ' ', '_', $aFilename);
     $md5 = md5($aFilename); 

     return "https://upload.wikimedia.org/wikipedia/commons/" .
            substr($md5,0,1) . 
            "/" .
            substr($md5,0,2). 
            "/" . 
            urlencode($aFilename);
 }    
 
 ```
taken from here: https://stackoverflow.com/questions/34393884/how-to-get-image-url-property-from-wikidata-item-by-api

in short: i think to take the filename from wikidata, extract it and use it with 'https://upload.wikimedia.org/wikipedia/commons/' + hash-sum + filename with uri-replacements
would create a more stable output

**Comment by csae8092** [comment]
I'll remove the `&width` param and urlencode the filename
URL will looking something like `https://commons.wikimedia.org/w/index.php?title=Special:Redirect/file/Theo.%20Komisarjevsky%20LCCN2014715267.jpg`
