### ISSUE TITLE
mockup of a more thorough redesign

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#120]
Thinking about it on a more general scale it would make sense to highlight the main entity and make the relations visibly the second layer. That could be achieved like this:
* background-colour for the left column
* max width for the left column that is 750px

the right column takes over what ever there is left and starts visibly lower than the left

e.g. a quick mockup with the title of the entity also moved to the left column. that is not necessary. but the "Beziehungen" nevertheless should start 2–3 cm below the coloured frame

![mockup](https://github.com/arthur-schnitzler/pmb-service/assets/11441262/3bb74761-4c4a-4d72-91fd-0a99cc9cc097)

**Comment by csae8092** [comment]
I'd say the current layout is fine enough
