### ISSUE TITLE
dates in search results table

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#128]
If a person has years only in their lifespan this is shown as either "-07-01" or "-07-02".
 
<img width="721" alt="Bildschirmfoto 2024-01-29 um 15 12 39" src="https://github.com/arthur-schnitzler/pmb-service/assets/11441262/a2f608a4-0572-40ea-ac6c-c58a0180033f">

this makes it nearly impossible to match duplicate birth dates. better would be to show only the year

**Comment by martinantonmueller** [comment]
sorry, this was not expressed properly. so as far as i'm aware there are two fields, date-iso and date-written.

if date-written is present i would
1) `<sortdate hidden="true">{date-iso}</sortdate>` + date-written (before the part in `<…>`)

if date written is empty 
`<sortdate hidden="true">{date-iso}</sortdate>` + `date-iso`

thus the possibilty to sort after iso date would be kept even though it's showing date literal

**Comment by csae8092** [comment]
as the sorting is done server side unlike in e.g. schnitzler-briefe your suggested solution does not work here. But for sorting you can always toggle the additional colum `start_date` and sort using this e.g. https://pmb.acdh.oeaw.ac.at/apis/entities/entity/person/list/?name=Mildenburg&columns=start_date&sort=start_date

but let's discuss this IRL
