### ISSUE TITLE
remove "Abbildung" and empty frame if no image is available

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#132]
I think it's self explanatory thus I would skip `<th>Abbildung</th>` in the detail view. 

And if there is no image available it should not show anything (currently empty frame with broken link symbol)

**Comment by csae8092** [comment]
second thing already fixed https://github.com/arthur-schnitzler/pmb-service/commit/6328598abb22665f7ec088722c3039a9d22b03e4
first thing I'd like to keep because know finally everything is aligned properly

**Comment by martinantonmueller** [comment]
great! – for the first thing: adding a fixed empty space `&#160;` should do the trick: th would not be empty and the alignment should be kept
