### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#147]
@csae8092 created two lists with duplicates, duplicated_persons.csv and duplicated_places.csv

duplicated persons can be applied

duplicate places would need more refinement, as the first lines already show that hotels with them same hotel are seen as the same but of course are not.

**Comment by csae8092** [comment]
@martinantonmueller created a new list of potential duplicated places, now lat/lng are compared as well

**Comment by martinantonmueller** [comment]
Wow!

Am 15.02.2024 um 17:09 schrieb Peter Andorfer ***@***.***>:

﻿
External Email: please use links and attachments from trusted sources only

@martinantonmueller<https://github.com/martinantonmueller> created a new list of potential duplicated places, now lat/lng are compared as well

**Comment by martinantonmueller** [comment]
Where can I find the new list?

**Comment by csae8092** [comment]
> Where can I find the new list?

In the usual place in two, three hours

**Comment by csae8092** [comment]
merge script a couple of days ago, closing this now
