### ISSUE TITLE
create wikidata importer for organisations

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#160]
Here are five examples:

https://www.wikidata.org/wiki/Q2919142 (Zeitung)
https://www.wikidata.org/wiki/Q308720 (Theater)
https://www.wikidata.org/wiki/Q7191 (Preis)
https://www.wikidata.org/wiki/Q557116 (Firma)
https://www.wikidata.org/wiki/Q151030 (Theater in Paris)

The import routine should fill out the title-field ("de" if available, otherwise "en", otherwise "fr", "it", "es", that should cover all)

start-date = inception = https://www.wikidata.org/wiki/Property:P571

and if it exists – a relation "angesiedelt in" to headquarter location https://www.wikidata.org/wiki/Property:P159

**Comment by csae8092** [comment]
> The import routine should fill out the title-field ("de" if available, otherwise "en", otherwise "fr", "it", "es", that should cover all)
choosing the language is not possible in the current set up, therefore you'll have to change names manually if the created name is not in the expected language
