### ISSUE TITLE
new menu item for downloads and  for visualisation 

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#161]
this is just so that i have something to do as well. peter yesterday made several export files. they need description. and do we already link to apis-hub?

**Comment by martinantonmueller** [comment]
hab’ jetzt einmal eine datei export.html angelegt. alles weitere betrifft dich, @csae8092

**Comment by csae8092** [comment]
closed with https://github.com/arthur-schnitzler/pmb-service/commit/e5e5dc37c4b845003e2468f16c970ff449fbb2e3
