### ISSUE TITLE
Bahr-URIs

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#166]
Please delete all URIs starting with: "https://hermanbahrtextverzeichnis" and "https://this-will-change/"

and instead upload these URIs:
https://docs.google.com/spreadsheets/d/1prs6ih08rQ5-n4OXotfMp6RMTWBDIYKtD-MF9sQ3Mwo/edit?usp=sharing

**Comment by martinantonmueller** [comment]
Merci!

**Comment by martinantonmueller** [comment]
Is it possible to change the type of the URIs containing "TSN-listperson" to something other than "bahr-textverzeichnis", maybe "bahr-TSN"?

**Comment by martinantonmueller** [comment]
just in case it would help: I have added a third column to the google-docs above containing the type of URI

**Comment by csae8092** [comment]
I guess by "type" you mean domain? Sure, can do. Btw, what does TSN stand for?

**Comment by martinantonmueller** [comment]
Great! Yes, "domain". I'm referring to the TEI-export, there it is "@subtype".
TSN = Tagebücher, Skizzenbücher, Notizhefte; the title of the books for which the index is for

**Comment by martinantonmueller** [comment]
This did not work properly, now all URI-Domains are renamed to "bahr-tsn" while it should be:

bahr-textverzeichnis: https://bahr-textverzeichnis.acdh.oeaw.ac.at/pmb122567.html

bahr-TSN: https://bahr-textverzeichnis.acdh.oeaw.ac.at/TSN-listperson.html#pmb159046
