### ISSUE TITLE
Duplicates from Wikidata-reconciliation

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#169]
EM Dammerer has sent another list of duplicates. I've sorted it so that the left column has the ID that stays and the right one the ID that merges into the lower number. 

https://docs.google.com/spreadsheets/d/1uP_Nnyku-9mvINKeuggyjh2t3VZkK4kJGsPm0xueI1o/edit#gid=582129900

@csae8092 can this be done automatically or shall we do it?

**Comment by martinantonmueller** [comment]
you're the best!

**Comment by csae8092** [comment]
need to run the script on the serve still, which can happen only tomorrow

**Comment by martinantonmueller** [comment]
Emmanuel just send another 170 duplicates. I copied them in the same gSheet so that all you have to do is to run the script a second time? Thank you!

https://docs.google.com/spreadsheets/d/1uP_Nnyku-9mvINKeuggyjh2t3VZkK4kJGsPm0xueI1o/edit#gid=1069211529

**Comment by csae8092** [comment]
did we already mention Emmanuel somewhere on PMB as almost most valuable PMB-Member?

**Comment by martinantonmueller** [comment]
Yes, we did! Just two hours before you noticed: https://github.com/acdh-oeaw/pmb-service/commit/ccbcc4a5f25bbfcc6243e94bbb4a6e10196ebb70
