### ISSUE TITLE
data imports

### ISSUE THREAD

**Issue by csae8092** [arthur-schnitzler/pmb-service#17]
https://github.com/hermann-bahr/bahr-textverzeichnis-data/blob/main/data/indices/listperson.xml
https://github.com/hermann-bahr/bahr-index/blob/main/tsn/listPerson_TSN_1.xml

**Comment by martinantonmueller** [comment]
and additionally after that 
https://github.com/hermann-bahr/bahr-index/blob/main/tsn/listwork_TSN_1.xml
uris are temporary as everything will get pmb-uris. but in general this gives the pmb a third leg after schnitzler and kraus – hermann 'the guy from the day after tomorrow' bahr

**Comment by csae8092** [comment]
na, tsn ist eigentlich nicht bahr-textverzeichnis sondern das hier: https://bahr.univie.ac.at/node/49702. Entweder nix oder, wenn das geht in "reference" das so auflösen
Hermann Bahr: Tagebücher, Skizzenbücher, Notizhefte. Hg. Moritz Csáky. Wien, Köln, Weimar: Böhlau 1994-2003, I, S. 11
etc. etc.

**Comment by martinantonmueller** [comment]
Das gilt natürlich auch für die TSN-Personen. Sauber wäre, wir würden den Verweis angeben. Und damit wäre die PMB als Generalregister für die Bände zu benutzen und die verlinkte univie-Seite obsolet

**Comment by martinantonmueller** [comment]
We need to revisit this issue as this created an incredible amount of useless data: 
https://pmb.acdh.oeaw.ac.at/apis/entities/entity/person/2292/detail
Either we go back to one title for the complete edition and then just the vols. and pages (i.e. I, 233) or at least mention only the volumes in which a person is mentioned, which would mean at most 5 titles

**Comment by martinantonmueller** [comment]
Or easier still: Write "Hermann Bahr: Tagebücher, Skizzenbücher, Notizhefte. Hg. Moritz Csáky. Wien, Köln, Weimar: Böhlau 1994-2003, https://bahr.univie.ac.at/node/49702" that way the register is linked and forget everything else

**Comment by martinantonmueller** [comment]
And easier still: we create an URI that links to "https://bahr.univie.ac.at/node/49702" plus some random text afterwards, i.e. 
https://bahr.univie.ac.at/node/49702?URI=TSNperson11122
that way the link works and everyone can look for the page numbers

**Comment by csae8092** [comment]
I was thinking of creating PMB-Works for all of those volumes and linking the entities properly via PersonWork Relation with a type "erwähnt" in and writing the exact page number(s) into the reference field of the relation; by doing so we can answer questions like which person/work is referenced how often

**Comment by martinantonmueller** [comment]
This of course would work but I don't think we should start with this. The questions you asked are possible to solve by using the listperson and listbibl. Can we just make it easy? Remove the huge amount of text and I give you a list of URIs which I need to give you for the Textverzeichnis anyways? I think that's the quickest solution
