### ISSUE TITLE
TEI-export APIS dates

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#174]
the current cleanup is not valid TEI:
<img width="666" alt="Bildschirmfoto 2024-03-07 um 09 01 22" src="https://github.com/arthur-schnitzler/pmb-service/assets/11441262/2cb757c3-7da4-4e96-92dd-6c9b6241ba48">

the error code says: `The @when attribute cannot be used with any other att.datable.w3c attributes.`

solution would be to exchange `when` with `when-iso`

**Comment by martinantonmueller** [comment]
side note: funny enough, both attributes, `@notBefore`and `when-iso` would allow a four digit value "1854"

**Comment by csae8092** [comment]
can you please post a link to this entity?

**Comment by martinantonmueller** [comment]
I'm sorry, this seems to have been an earlier export. At least I cannot find it anymore
