### ISSUE TITLE
Import wikidata-URIs 

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#181]
Emanuel created several wikidata-entries based on PMB-entries. Now we can add their wikidata identifiers to PMB:

Here is a list of wikidata-URIs missing in PMB (but existing in wikidata):

https://docs.google.com/spreadsheets/d/1prs6ih08rQ5-n4OXotfMp6RMTWBDIYKtD-MF9sQ3Mwo/edit#gid=183308257

**Comment by martinantonmueller** [comment]
As the workflow was rather simple and similar I've matched wiengeschichtewiki-URIs with pmb-uris via wikidata. There is a second sheet in the gsheet above with info on the pmb-number and the corresponding wiengeschichte-uri. please import as well

**Comment by martinantonmueller** [comment]
finally I've added a third sheet with uris for schnitzler-zeitungen and schnitzler-mikrofilme to be imported. I just added the pmb-number after "?" to make the uris distinct.

**Comment by csae8092** [comment]
hm, I'll wait a couple days longer, maybe some more sheets pop up ;)

but could you please create a gsheet per sheet, so I can address every sheet via its own URL
