### ISSUE TITLE
Geonames badge without background color

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#183]
https://pmb.acdh.oeaw.ac.at/apis/entities/entity/place/40454/detail

![Bildschirmfoto 2024-04-24 um 09 33 11](https://github.com/arthur-schnitzler/pmb-service/assets/11441262/95e06bfd-3081-4fad-882c-1a836ecc4b6e)
![Bildschirmfoto 2024-04-24 um 09 33 06](https://github.com/arthur-schnitzler/pmb-service/assets/11441262/e1e353c3-cbb9-4aab-a16d-296af8eaf6a2)

**Comment by csae8092** [comment]
please adapt https://github.com/arthur-schnitzler/pmb-service/blob/main/pmb/settings.py#L313 to your needs

**Comment by martinantonmueller** [comment]
all I had to do was to remove a "#"
