### ISSUE TITLE
import schnitzler-briefe-uris

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#188]
dear @csae8092 – could you at some point delete all schnitzler-briefe-uris and replace them with this:
https://docs.google.com/spreadsheets/d/1VXXj7tc4sy52KpV_II4gIYmVUQ-lSLi-S8XqBsBMlCE/edit?usp=sharing

it might very well be that this is the last time in this project

**Comment by csae8092** [comment]
@martinantonmueller  hm, https://schnitzler-briefe.acdh.oeaw.ac.at/2206.html gibts aber nicht; und wenn sich die URI aus der XML:ID der Entität ergibt, dann sollte die XML:ID auch nicht mit einer Zahl beginnen

**Comment by martinantonmueller** [comment]
uppsi, habe ich das vorangestellte pmb vergessen gehabt. ist behoben! danke!
