### ISSUE TITLE
replace bahr-textverzeichnis URIs 

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#191]
lieber Peter, wie im anderen Kanal besprochen, hier die Liste der personen-URIs für Bahrs Textverzeichnis neu:

https://docs.google.com/spreadsheets/d/1VXXj7tc4sy52KpV_II4gIYmVUQ-lSLi-S8XqBsBMlCE/edit#gid=688748979

*ACHTUNG* das betrifft nur Personen in der PMB, die restlichen bahr-textverzeichnis-URIs bleiben erhalten. Wenn das nicht gehen sollte, gib’ bitte Bescheid, dann kommt eine komplette Liste.

Danke!

**Comment by csae8092** [comment]
Eine komplette Liste wäre tatsächlich einfacher für mich zu verarbeiten.

**Comment by martinantonmueller** [comment]
now the list is complete, so all URIs beginning with "https://bahr-textverzeichnis" can be deleted and replaced by the ones above
