### ISSUE TITLE
Delete unused professions

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#195]
There seem to be some professions that need to be deleted. The reason (probably) was that the last time we cleaned the professions this was done without deleting the unused professions. Now we have a corrupt vocabulary with entries such as »Graf von, Ps. Freiherr von Schlicht« 

The easiest solution would be to delete all professions with not at least one entry that uses it. @csae8092 is that possible?

Alternatively I could produce a list of all used professions and we could handle from there.

**Comment by csae8092** [comment]
> The easiest solution would be to delete all professions with not at least one entry that uses it. @csae8092 is that possible?

This should be possible, although I should not forget parent profession which might not be linked to an entity; do such parent professions exist?

**Comment by martinantonmueller** [comment]
Difficult for me to check. But the items to be deleted have no parent profession. So that could narrow it down. Would it be a problem if a profession has a parent profession that was deleted? If not you could just go ahead and delete the parent professions without a single occurence too

**Comment by csae8092** [comment]
those professions are not linked to any person; does this makes sense? @martinantonmueller and are there some nonsense profession missing?
[hansi.csv](https://github.com/arthur-schnitzler/pmb-service/files/15471621/hansi.csv)

**Comment by martinantonmueller** [comment]
Very much! Go for it!

Am 28.05.2024 um 16:43 schrieb Peter Andorfer ***@***.***>:

﻿
External Email: please use links and attachments from trusted sources only

those professions are not linked to any person; does this makes sense? @martinantonmueller<https://github.com/martinantonmueller>
hansi.csv<https://github.com/arthur-schnitzler/pmb-service/files/15471621/hansi.csv>
