### ISSUE TITLE
the return of the relations

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#210]
Currently it has become quite impossible to find specific relations. E.g. you want to know who was in Budapest in 1885:
https://pmb.acdh.oeaw.ac.at/apis/entities/entity/place/43471/detail
you can try sorting and then go through page after page. But the sorting is not 100% reliable

so it would be a relevant upgrade if the tables in pmb could be represented as tabular-tables with the possibility to enter "1885" in the filter on top

**Comment by csae8092** [comment]
this won't work (easy enough for me), but I want to recreate the relation list/detail views (as in the old application)
