### ISSUE TITLE
pmb import

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#212]
lieber @csae8092,

falls du mal zeit hättest, könntest du diese tabelle importieren? danke! es sind nur aufenthalte von schnitzler und anderen an bestimmten orten. eventuell gibt es einzelfälle, wo es die beziehung schon gibt, das kann ich nicht gut überprüfen. aber vielleicht läuft der import auch einfach durch?

https://docs.google.com/spreadsheets/d/13ZccvGh6nZwL4h8ZKn8W9COGtRjVVZT6gu4EtyW9Bi8/edit?usp=sharing

das ist auch ein testlauf, also wenn das so klappt, käme in nächster zeit noch mehr…

**Comment by csae8092** [comment]
folgende orte scheint es in der pmb nicht zu geben
{91552, 169126, 169129, 57161, 57325, 91711, 92239, 90290, 185877, 42649, 92987, 51868, 90845, 37214, 37183}

**Comment by martinantonmueller** [comment]
merci für den import! ich kümmere mich um die fehlenden orte – hab’ ich viel gemerged, vermutlich
