### ISSUE TITLE
Some more PMB-Import (currently preparatory state)

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#213]
This doc contains some relations between Schnitzler an places. 
https://docs.google.com/spreadsheets/d/1-_WXbdmpLzz_9vBiZ1y9v2tle_26m4tAhPTGzkkin5E/edit?usp=sharing

@martinantonmueller should add the ones he notes in a local spreadsheet on his pc

when @laurauntner prepares the import of schnitzler-kino there will be several more relations to be imported:
event -> place
event -> work
event -> persons ['teilgenommen an']

but before that events have to be imported. I'm afraid we'll have to do once more with temporary uris: give every event an identifier, ask @csae8092  to import it and get pmb-number in return.

**Comment by martinantonmueller** [comment]
I've added the relations person -> work from the new pmb-works

**Comment by martinantonmueller** [comment]
the question for me is only: does this make it easier for you, @csae8092? is this a table that can easily be imported?

**Comment by martinantonmueller** [comment]
i've added everything I have for now. it's currently over 3000 lines and all of schnitzlers whereabouts until 1895.

**Comment by csae8092** [comment]
@martinantonmueller ingested

**Comment by martinantonmueller** [comment]
oh, wow! thank you! then i delete the current content and we will fill it up again!

**Comment by csae8092** [comment]
could you please close this issue and create a new one for follwoing tasks

**Comment by martinantonmueller** [comment]
definitely!
