### ISSUE TITLE
import brahms personen

### ISSUE THREAD

**Issue by csae8092** [arthur-schnitzler/pmb-service#223]
https://brahms-online.oeaw.ac.at/Personenregister-verkuerzt.html

**Comment by martinantonmueller** [comment]
Cool, hat funktioniert! https://pmb.acdh.oeaw.ac.at/apis/entities/entity/person/27633/detail

**Comment by csae8092** [comment]
Ab ins Bett 😪!!!

**Comment by martinantonmueller** [comment]
hab’ kein fieber!
