### ISSUE TITLE
filter years in relations-table

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#226]
this is maybe the unwesentlichste bug ever, but for the records sake let this be noted: the filtering of years does not work
<img width="1079" alt="Bildschirmfoto 2024-10-14 um 11 34 50" src="https://github.com/user-attachments/assets/58529c13-d0ec-4e2c-892e-094c5e3dbaaf">

**Comment by martinantonmueller** [comment]
it does work though if I enter "1895" twice

**Comment by csae8092** [comment]
Its a date range filter, so you'll have to populate both fields

**Comment by martinantonmueller** [comment]
but how can I insert a date-range when there is only "year" allowed?
