### ISSUE TITLE
import theatre titles

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#227]
dear @csae8092, before we fill up #213 could you please at some point import the sheet with the works in the same google-sheet https://docs.google.com/spreadsheets/d/1-_WXbdmpLzz_9vBiZ1y9v2tle_26m4tAhPTGzkkin5E/edit?usp=sharing

if you return me the pmb-numbering in the correct order we don't really need the uris to be stored. 

thank you!

**Comment by csae8092** [comment]
Can you please create separate gsheet because I can't easily deal with multiple sheets in one gsheet

**Comment by martinantonmueller** [comment]
oopsie, thery you go: https://docs.google.com/spreadsheets/d/1wgLHBHeJECkmgJUIpPdG-JS8F-0ht_LdVTxNmWwW8O0/edit?gid=297726714#gid=297726714

**Comment by csae8092** [comment]
do they have worktype?

**Comment by csae8092** [comment]
doubletten?

schnitzler-theater-interim-titel-284 | Der Jourfix
-- | --
schnitzler-theater-interim-titel-285 | Der Jourfix



schnitzler-theater-interim-titel-1895 | Beethoven-Zyklus
-- | --
schnitzler-theater-interim-titel-1896 | Beethoven-Zyklus
schnitzler-theater-interim-titel-1897 | Beethoven-Zyklus


schnitzler-theater-interim-titel-477 | Seidl und Wiesberg
-- | --
schnitzler-theater-interim-titel-478 | Seidl und Wiesberg

**Comment by martinantonmueller** [comment]
No work-type, maybe Dubletten. But I clear that manually

**Comment by csae8092** [comment]
[theater-uris.csv](https://github.com/user-attachments/files/17395111/theater-uris.csv)
https://pmb.acdh.oeaw.ac.at/apis/entities/entity/work/list/?collection=29

can this be closed?

**Comment by martinantonmueller** [comment]
not before I say thank you!
