### ISSUE TITLE
the huge relations import-sheet

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#228]
this is the gsheet:
https://docs.google.com/spreadsheets/d/1-_WXbdmpLzz_9vBiZ1y9v2tle_26m4tAhPTGzkkin5E/edit?usp=sharing

once it's filled we will let peter know

**Comment by martinantonmueller** [comment]
i've added all relations up to and including 1899

**Comment by laurauntner** [comment]
renamed the sheet, it’s now called schnitzler-new-relations

**Comment by laurauntner** [comment]
added relations (kino-events + movie-relations). kino-events (»Filmvorführung«) have to be matched using the (distinct) titles.

**Comment by martinantonmueller** [comment]
that's incredible! 10.000 relations more! but before the import can take place we will have to have the new event-import and then replace the eventName with the actual number. (what laura says. just to make clear that it's not up to peter yet)

**Comment by laurauntner** [comment]
replaced titles with pmb-ids. don’t know if you want to add anything else, @martinantonmueller, but i'm done.

**Comment by martinantonmueller** [comment]
yes, i want to do some more stuff tomorrow.

**Comment by martinantonmueller** [comment]
this is it! i’m done! we're close to 20.000 new relations for the PMB. if that doesn't crash it, what else will? – do your magic, @csae8092 ! thank you for everything!
