### ISSUE TITLE
Sort relation views newest to oldest ID

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#229]
The initial sort order of the relation views should always be on the ID, i.e. showing the last created relations on top. This is currently shown _after_ a relation is created but it would be better to have that as the normal sorting as well.

**Comment by csae8092** [comment]
Maybe easy to fix here somewhere apis_core/apis_relations/utils.py

**Comment by martinantonmueller** [comment]
there is: 
https://pmb.acdh.oeaw.ac.at/apis/relations/person-place/?&sort=-updated
