### ISSUE TITLE
Event-Types export

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#233]
dear @csae8092, could you produce an export of all the 101 event-types with their number? Unfortunately the csv-export in the django-environment doesn’t work.

**Comment by csae8092** [comment]
[event-types.csv](https://github.com/user-attachments/files/17554578/event-types.csv)

**Comment by csae8092** [comment]
[event-types.csv](https://github.com/user-attachments/files/17554719/event-types.csv)
here a list with how often each type is used

**Comment by martinantonmueller** [comment]
Thank you! That second list is going to change. I am preparing a list of over 3.000 events that I will ask you to import
