### ISSUE TITLE
PMB-import theatre and cinema events

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#234]
Dear @laurauntner,

I’ve prepared a Google Sheet for the import of all of Schnitzler's theater visits:
[https://docs.google.com/spreadsheets/d/1NAyAetEWR1RzyGcdTWc0KGK2ip19PpSyIOBBCOnyRnA/edit?gid=0#gid=0](https://docs.google.com/spreadsheets/d/1NAyAetEWR1RzyGcdTWc0KGK2ip19PpSyIOBBCOnyRnA/edit?gid=0#gid=0)

Could you add your cinema visits to this sheet and then kindly ask @csae8092 to proceed with the import?

Thanks to him, there’s now an "event-types" file in the meta-folder in case you need it.

I’ve left out a temporary URI since each event title is unique, so there should be no problem with matching afterward. However, if it’s different on your end, could you create a temporary URI for mine as well by adding a column in the Google Sheet?

Thank you!

**Comment by laurauntner** [comment]
alright! can we close #228 now?

**Comment by martinantonmueller** [comment]
no, we will need #228 to fill it up with relations for import

**Comment by laurauntner** [comment]
added the kino-events (without temporary uris). 

@csae8092 we would be ready for this import now :) relations will follow soon

**Comment by csae8092** [comment]
coming in hot today or tomorrow...

**Comment by martinantonmueller** [comment]
Sorry, @csae8092, could you hold the press for a second? I just asked @laurauntner to rename her event-titles and remove the whitespace in them.

**Comment by laurauntner** [comment]
done

**Comment by csae8092** [comment]
@martinantonmueller  @laurauntner event kind kann es nur einen geben, -> ich nehme da jetzt den ersten wert
z.B. 
> 1891-02-21 | 1891-02-21 | 1891-02-21 | 1891-02-21 | Diner und Soirée Weiss-Wellenstein, 21.2.1891 | 3656 4292

**Comment by csae8092** [comment]
[events-pmb_ids.csv](https://github.com/user-attachments/files/17619100/events-pmb_ids.csv)

**Comment by martinantonmueller** [comment]
perfect, thank you!
