### ISSUE TITLE
PMB performance

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#236]
Talking of beschissene performance: This morning PMB was working like a charm. Then somewhen around noon it became nearly unusable. Could it be the deployment of the Wikidata-Importer for works? Or is it the usual up and down? 

And maybe another thing i noticed: When I import a place via wikidata-URI i get a PMB-URI and the number is written in the URL-field. But when I immediately update the place (i.e. add place-type) and press safe the URI changes back to an URI that says importing (without the pmb-number), just as if the import would not have taken place already. This appears strange to me. But probably it's nothing

**Comment by martinantonmueller** [comment]
ok, now, after 90 mins or so everything is good again

**Comment by martinantonmueller** [comment]
and since 16:00 it's total crap again

**Comment by martinantonmueller** [comment]
Currently it takes 25 seconds to create a new entry and the same amount for a new relation to person or place (the other relations slightly faster?)

**Comment by martinantonmueller** [comment]
Add another 25 seconds to get to the "create new relation"-page.

**Comment by martinantonmueller** [comment]
Ha, now I had a fast one and everything went smooth.

**Comment by martinantonmueller** [comment]
currently it's going ok. not fast but not unbearable slow

**Comment by martinantonmueller** [comment]
we're back to unbearable slow

**Comment by martinantonmueller** [comment]
And now fast again

**Comment by martinantonmueller** [comment]
Slow it is

**Comment by martinantonmueller** [comment]
It continues to be a drag

**Comment by martinantonmueller** [comment]
back again, now it's working

**Comment by martinantonmueller** [comment]
and immediately bad again

**Comment by martinantonmueller** [comment]
currently it's slow but at least not bad-bad

**Comment by martinantonmueller** [comment]
it works

**Comment by martinantonmueller** [comment]
and it's over

**Comment by martinantonmueller** [comment]
it did work for a second, though

**Comment by martinantonmueller** [comment]
currently it works, more or less for the last 30 minutes

**Comment by martinantonmueller** [comment]
you write something nice and it immediately stops working. that's how it is

**Comment by martinantonmueller** [comment]
a new day, a new slow beginning

**Comment by martinantonmueller** [comment]
today it's a slow day. not terrible but not good either

**Comment by martinantonmueller** [comment]
ok, it's not good

**Comment by martinantonmueller** [comment]
don't leave for lunch. afterwards it is as bad as ever

**Comment by martinantonmueller** [comment]
it did work a little. but now I can write messages in between without anything happening on the site

**Comment by martinantonmueller** [comment]
actually you can start to write short stories

**Comment by csae8092** [comment]
although I'd been curious to read some short stories written while waiting for pmb maybe https://github.com/arthur-schnitzler/pmb-service/commit/2b5d55174f50326addfa6b092eb34c1df2cb844e and ff prevent them now from ever being written.

**Comment by martinantonmueller** [comment]
I should have gone back to Twitter and would have gained a substantial amount of followers by the time I was finished waiting.

**Comment by csae8092** [comment]
Maybe this will become the next twitter?

**Comment by martinantonmueller** [comment]
Maybe! Hopefully there will be more threads though
