### ISSUE TITLE
some pmb-corrections

### ISSUE THREAD

**Issue by laurauntner** [arthur-schnitzler/pmb-service#237]
while working on schnitzler-kino, i noticed a few incorrect titles and dates in the pmb. additionally, i found new wikidata uris and imdb uris for some entities. i’ve written all the correction data in a list: https://docs.google.com/spreadsheets/d/1-Kl0pFsiABqzNZ65PoGp2SWrGadcRega-DIs_NxLcHE/edit?usp=sharing

could you correct the pmb accordingly, @csae8092 ?

**Comment by laurauntner** [comment]
@martinantonmueller fyi

**Comment by martinantonmueller** [comment]
I have no clue if @csae8092 can handle this or if we need to split it into different lists:
1) entry plus new URI
2) list of wrong URIs
3) list of new titles
but this is just me guessing, Peter will let us know

**Comment by csae8092** [comment]
gleich am anfang zwei kaputte imdb uris @laurauntner 
 
195403 |   | 1914 |   | https://www.imdb.com/title/ |  

sind das alle neue URIS, oder gibts zu manchen einträgen schon wikidata/imdb uris die aber falsch sind und mit denen aus der liste überschrieben werden müssen
falls alles neues uris sind

sollte aber alles mit der tabelle in der aktuellen form machbar sein

**Comment by laurauntner** [comment]
sorry, habe die links korrigiert.

die uris sind alle neu, bei titeln und daten handelt es sich hingegen um korrekturen.

**Comment by laurauntner** [comment]
thank you, @csae8092 :)
