### ISSUE TITLE
some notes to events

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#238]
as schnitzler left some notes on the theatre list it would be a pity if they got lost: 
https://docs.google.com/spreadsheets/d/1mzXwjYjwKfvADur9hcrY6L1IPpMttEYOHgKFQP2kDTw/edit?usp=sharing
could you import them into the MetaInfo -> Notes field 

(and rest assured, there won't be as much to import in the future) thanks a lot!

**Comment by csae8092** [comment]
can do, will do
