### ISSUE TITLE
default sort of entites by last-edited?

### ISSUE THREAD

**Issue by csae8092** [arthur-schnitzler/pmb-service#244]
Currently, all entity list views are sorted by ID, which causes Schnitzler to always appear first. I’d personally prefer sorting by last update, as it would shift the app’s focus (and that of all bots) to the most recently updated entities.

@martinantonmueller any thoughts?

**Comment by martinantonmueller** [comment]
I thought of that as well! You're reasoning resonates with my feelings on the matter. I follow your judgment

**Comment by csae8092** [comment]
closed with https://github.com/arthur-schnitzler/pmb-service/commit/c1a0c71dcb6ea2330d10ee836e719ada21f9facd
