### ISSUE TITLE
it's a merry little xmas-import

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#281]
lieber peter, in the spirit of the season und wissend und fürchtend, dass in der stillen zeit leerläufe entstehen könnten – dürfte ich dich wieder einmal um einen pmb-import von beziehungen bitten:

https://docs.google.com/spreadsheets/d/1F7Ha6gkYmjtxjNguAuKEP3slbedAQkPWfHO1NG3QnpA/edit?usp=sharing 

möge dafür der platz unterm christbaum zu eng werden für all’ die geschenke, die du (nicht von mir) bekommst!

**Comment by csae8092** [comment]
gitb keine apis entity mit id 90368

**Comment by martinantonmueller** [comment]
Ho, ho, ho! Vielen Dank!
