### ISSUE TITLE
import emt persons

### ISSUE THREAD

**Issue by csae8092** [arthur-schnitzler/pmb-service#282]
https://emt.acdh-dev.oeaw.ac.at/listperson.xml
only those with normdata; I know they don't really fit the pmb-scope; but we talking about ~ 300 persons; so who would notice...

**Comment by csae8092** [comment]
and we have some overlap https://pmb.acdh.oeaw.ac.at/apis/entities/entity/person/151278/detail

**Comment by martinantonmueller** [comment]
🥳
