### ISSUE TITLE
show only subclasses in dropdowns

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#61]
limit the view of the classes to the lowest class, without showing the ancestry (Berufe, relation types…)

**Comment by csae8092** [comment]
should be closed with https://github.com/acdh-oeaw/pmb-service/pull/31

**Comment by csae8092** [comment]
hm, maybe reverse relations are displayed still wrong?

**Comment by martinantonmueller** [comment]
yes, reverse relations are still displayed wrong. guckstu hier:
https://pmb.acdh.oeaw.ac.at/apis/entities/entity/person/14948/detail
