### ISSUE TITLE
edit view does not show URIs

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#77]
the uris are visible in the detail view only, but it would make sense to see them in any case

**Comment by csae8092** [comment]
if logged in, there are now links from an entities detail view to the uris edit/delete views

**Comment by martinantonmueller** [comment]
this is not what i meant (?) – I would like to be in "edit view" and see if the person is mentioned in Schnitzler’s diary etc. currently in edit view one does not see the uris and has to change to "detail view" to see them

**Comment by csae8092** [comment]
try to find an easy to create/maintain solution which makes @martinantonmueller happy

**Comment by martinantonmueller** [comment]
I am happy! I could be more happy though! But if it's difficult – then it's not worth the hassle
