### ISSUE TITLE
standardize URIs ANNO and Wien Geschichte Wiki

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#78]
We could make the labels "Wien Geschichte Wiki" and "Werk-Link Anno" obsolete by upgrading all labels to be URIs.

**Comment by csae8092** [comment]
@martinantonmueller can you please check https://pmb.acdh.oeaw.ac.at/apis/metainfo/apis/metainfo/uri/?domain=anno and https://pmb.acdh.oeaw.ac.at/apis/metainfo/apis/metainfo/uri/?domain=geschich if this is as you wished. If so, please confirm and I'll delete the anno- and wienwiki labels?

**Comment by martinantonmueller** [comment]
Thank you! I've deleted the wiengeschichte-labels myself. so that is done. I'm having second thoughts about the anno-links as they are not really URIs and much more fragile. so maybe we leave them the way they were? or do you have another opinion? @csae8092

**Comment by csae8092** [comment]
lets keep uris and labels, we can remove the uris when they don't resolve anymore

**Comment by martinantonmueller** [comment]
tiny thing: now anno is duplicated, once as a label, once as a URI. could you please bulk delete the URIs?
