### ISSUE TITLE
adapt all professions to "male profession/female profession" and clear duplicates

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#80]
as the professions are not automatically imported anymore the final clean-up of the names should happen, making every profession work for both genders again (i.e. "Maler/Malerin"). We did this before, we have to do it again.

**Comment by martinantonmueller** [comment]
When I try to download a csv of all professions in the admin area I get a server 500-error. @csae8092 to the rescue!

**Comment by csae8092** [comment]
have you tried this
https://pmb.acdh.oeaw.ac.at/media/ [professions.csv](https://pmb.acdh.oeaw.ac.at/media/professions.csv)

**Comment by martinantonmueller** [comment]
oops! thank you!

**Comment by martinantonmueller** [comment]
@csae8092 i have now done some housekeeping:
this list names the profession ids, the new names and in the last columns ids that should be merged into this id-number:
https://docs.google.com/spreadsheets/d/1MnS_eJbPNLzXp4YkS5I9Xkhv2GVPbYtrFiQjJla5rJE/edit?usp=sharing
if I should deliver another format please let me know

**Comment by csae8092** [comment]
@martinantonmueller  could you please
* delete the sheet "professions-vierspaltig" 
* fix error around line 436
* join all duplicates into one column like

2134 | 2217 | 3130 | 3182 | 3421 | 3423
into |2134, 2217, 3130, ...|

**Comment by martinantonmueller** [comment]
which sheet? ;-)

**Comment by martinantonmueller** [comment]
@csae8092 all done!
