### ISSUE TITLE
potential duplicates found by checking/harmonizing https to http wikidata uris

### ISSUE THREAD

**Issue by csae8092** [arthur-schnitzler/pmb-service#81]
merging time

(<Uri: http://www.wikidata.org/entity/Q1781>, <TempEntityClass: Budapest (ID: 43471)>)
(<Uri: http://www.wikidata.org/entity/Q154010>, <TempEntityClass: Wieland (ID: 116532)>)
(<Uri: http://www.wikidata.org/entity/Q632381>, <TempEntityClass: Berliner Ensemble (ID: 142557)>)
(<Uri: http://www.wikidata.org/entity/Q329989>, <TempEntityClass: Die Dämonen (ID: 77735)>)
(<Uri: http://www.wikidata.org/entity/Q1417362>, <TempEntityClass: Fink und Fliederbusch. Komödie in drei Akten (ID: 30881)>)
(<Uri: http://www.wikidata.org/entity/Q1451452>, <TempEntityClass: Frau Beate und ihr Sohn. Novelle (ID: 32133)>)
(<Uri: http://www.wikidata.org/entity/Q703339>, <TempEntityClass: Jugend (ID: 44080)>)
(<Uri: http://www.wikidata.org/entity/Q874053>, <TempEntityClass: Verwaltungsgerichtshof (ID: 144488)>)
(<Uri: http://www.wikidata.org/entity/Q24312>, <TempEntityClass: Münchener Secession (ID: 144709)>)
(<Uri: http://www.wikidata.org/entity/Q753298>, <TempEntityClass: Onkel Wanja. Szenen aus dem Landleben in vier Akten (ID: 59338)>)
(<Uri: http://www.wikidata.org/entity/Q312576>, <TempEntityClass: Staatsoper Unter den Linden (Berlin) (ID: 37043)>)
(<Uri: http://www.wikidata.org/entity/Q821464>, <TempEntityClass: Berliner Börsen-Courier (ID: 41289)>)
(<Uri: http://www.wikidata.org/entity/Q512687>, <TempEntityClass: Die Schaubühne (ID: 41564)>)
(<Uri: http://www.wikidata.org/entity/Q1680528>, <TempEntityClass: Unterhaltungen deutscher Ausgewanderten (ID: 142587)>)
(<Uri: http://www.wikidata.org/entity/Q261757>, <TempEntityClass: Lessing-Theater (ID: 35053)>)
(<Uri: http://www.wikidata.org/entity/Q32487>, <TempEntityClass: Schiller-Theater (ID: 57124)>)
(<Uri: http://www.wikidata.org/entity/Q328191>, <TempEntityClass: Palasthotel Berlin (ID: 146840)>)
(<Uri: http://www.wikidata.org/entity/Q3148527>, <TempEntityClass: Il ne faut jurer de rien (ID: 145666)>)
(<Uri: http://www.wikidata.org/entity/Q1140265>, <TempEntityClass: Kungliga Dramatiska Teatern (ID: 147893)>)
(<Uri: http://www.wikidata.org/entity/Q1169370>, <TempEntityClass: Royal Court Theatre (ID: 147907)>)
(<Uri: http://www.wikidata.org/entity/Q168657>, <TempEntityClass: Albert von Sachsen (ID: 116982)>)
(<Uri: http://www.wikidata.org/entity/Q521155>, <TempEntityClass: Ständetheater (ID: 27)>)
(<Uri: http://www.wikidata.org/entity/Q115593>, <TempEntityClass: Schloss Hellbrunn (ID: 147319)>)
found 23 potential http/https duplicates

**Comment by martinantonmueller** [comment]
needs fix: https://github.com/arthur-schnitzler/pmb-service/issues/82

**Comment by martinantonmueller** [comment]
I suppose you did fix the ones where an entry had two wikidata-uris yourself, @csae8092 ? the others are fixed, so this can be closed now
