### ISSUE TITLE
TEI export "pmb" instead of "apis-default"

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#87]
before the pmb-uri in the export was:

`<idno type="URL" subtype="pmb">https://pmb.acdh.oeaw.ac.at/entity/13266/</idno>`

now it's reverted to "apis-default":

`<idno type="URL" subtype="apis-default">https://pmb.acdh.oeaw.ac.at/entity/148275/</idno>`

**Comment by csae8092** [comment]
@martinantonmueller  please check again and reopen if this issues still exists
