### ISSUE TITLE
have complete lists downloadable

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#96]
in Wikipedia we promote (?) this link:
https://pmb-service.acdh-dev.oeaw.ac.at/
to download all listperson, listplace etc. 
the link does not work anymore

**Comment by csae8092** [comment]
here all tei-lists can be found https://pmb.acdh.oeaw.ac.at/media/

**Comment by martinantonmueller** [comment]
i just added the url to wikipedia and now all the files are gone. but this is an open issue so I'm not complaining. just stating facts

**Comment by csae8092** [comment]
just be fixed with https://github.com/arthur-schnitzler/pmb-service/issues/100 after deploying new version, lets see...
