### ISSUE TITLE
Wikidata Importer person

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#97]
I tried to import this person – all leading to "Server Error (500)":
https://www.wikidata.org/wiki/Q2390830
https://www.wikidata.org/entity/Q2390830
https://www.wikidata.org/wiki/Special:EntityPage/Q2390830

I will not import the person manually now to have the error accessible but we will have to create him and a relation to his sister Wera afterwards

**Comment by csae8092** [comment]
see https://github.com/arthur-schnitzler/pmb-service/issues/40
