### ISSUE TITLE
disallow duplicate relations

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/pmb-service#99]
if a relation type and the time values are the same to an existing one it should not be possible to create the relation
* remove already existing duplicated relations
* something like [UniqueConstraint](https://docs.djangoproject.com/en/5.0/ref/models/constraints/#uniqueconstraint) on source, target, relation type might break current merging mechanism
* maybe just prevent duplicated relation creation via forms?

**Comment by martinantonmueller** [comment]
another benefit would be that duplicates happen more easily with the new pmb if one accidently presses the "save"-button twice

**Comment by martinantonmueller** [comment]
This needs further refinement. Currently it disallows duplicate relations of the same type. But it should check for the dates as well:
ino dates / no dates or exact same dates should be forbidden, but of course a relation with different dates should be possible. e.g. PersonX stays in Meran in 1892 and 1895 should be allowed

**Comment by csae8092** [comment]
hm, this is possible, see
https://pmb.acdh.oeaw.ac.at/apis/entities/entity/person/167791/detail

or am I missing something here?

**Comment by martinantonmueller** [comment]
Yes, sorry! It was an (honest) mistake in my part
